### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by KFlash** [mindoro/mindoro#3]
There are not much too do actually. Basically let this repo stay as an experimental project. As it actually is. 

Here is what to fix if this shouldnt stay as an experimental project

- [ ] Fix remaining scanner issues and TODO`s and location tracker

- [ ] Add grammar support. Just add bitmasks where it's needed to fail

- [ ] label tracking

- [ ] catch all early errors (*some are already catched*)

- [ ] Add revisited template support - ES2018

- [ ] Collecting of comments in the scanner

- [ ] Remove duplicate code and re-use functions if possible

**Comment by KFlash** [comment]
@isiahmeadows your thoughts?

**Comment by KFlash** [comment]
Closing as this is going to be fixed.
